import { writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dir = dirname(fileURLToPath(import.meta.url))
const statesDir = resolve(__dir, 'states')
mkdirSync(statesDir, { recursive: true })

function canonical(id: string, attrs: Record<string, string> = {}, locale = 'sv-SE'): string {
  const attrStr = Object.entries(attrs)
    .map(([k, v]) => v === '' ? k : `${k}="${v}"`)
    .join(' ')

  return `<div class="DateTimeField" data-component="DateTimeField" data-id="${id}" data-name="${id}" data-locale="${locale}" ${attrStr}>
  <input type="datetime-local" class="DateTimeField-native" tabindex="-1" aria-hidden="true">
  <div class="DateTimeField-overlay">
    <div class="Segments" role="group"></div>
    <button class="DateTimeField-trigger" type="button">
      <svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
        <line x1="16" y1="2" x2="16" y2="6"></line>
        <line x1="8" y1="2" x2="8" y2="6"></line>
        <line x1="3" y1="10" x2="21" y2="10"></line>
      </svg>
    </button>
  </div>
  <template class="DateTimeField-calendarTemplate">
    <div class="DateTimeField-popup" role="dialog" aria-modal="true">
      <div class="CalendarInner">
        <div class="CalendarLeft">
          <div class="CalendarHeader">
            <button class="CalendarPrev" type="button">&#8249;</button>
            <button class="MonthYearTrigger" type="button" aria-expanded="false"><span class="CalendarMonthYear"></span></button>
            <button class="CalendarNext" type="button">&#8250;</button>
          </div>
          <div class="Panel" data-panel="calendar" data-active="true">
            <table class="CalendarGrid" role="grid"></table>
          </div>
          <div class="Panel YearMonthPicker WheelColumns" role="group" data-panel="picker" data-active="false">
            <div class="Wheel" data-picker="month" tabindex="0"></div>
            <div class="Wheel" data-picker="year" tabindex="0"></div>
          </div>
        </div>
        <div class="TimeColumns WheelColumns">
          <div class="Wheel" data-segment="hour" tabindex="0"></div>
          <div class="Wheel" data-segment="minute" tabindex="0"></div>
          <div class="Wheel" data-segment="second" tabindex="0" style="display:none"></div>
          <div class="DateTimeField-ampm" role="group" hidden></div>
        </div>
      </div>
      <div class="CalendarFooter">
        <button type="button" class="CalendarFooterClear"></button>
        <button type="button" class="CalendarFooterToday"></button>
        <button type="button" class="CalendarFooterNow"></button>
      </div>
      <div class="arrow"></div>
    </div>
  </template>
  <div class="slideContainer"></div>
  <div class="Announce" aria-live="polite" aria-atomic="true"></div>
</div>`
}

const states: { name: string; id: string; attrs: Record<string, string>; locale?: string }[] = [
  { name: '_default', id: 'dtf-default', attrs: {} },
  { name: '_default-hover',  id: 'dtf-default-hover',  attrs: { 'data-test-state': 'hover' } },
  { name: '_default-focus',  id: 'dtf-default-focus',  attrs: { 'data-test-state': 'focus' } },
  { name: '_default-active', id: 'dtf-default-active', attrs: { 'data-test-state': 'active' } },
  { name: '_filled', id: 'dtf-filled', attrs: { 'data-value': '2026-05-27T14:35' } },
  { name: '_filled-hover',  id: 'dtf-filled-hover',  attrs: { 'data-value': '2026-05-27T14:35', 'data-test-state': 'hover' } },
  { name: '_filled-focus',  id: 'dtf-filled-focus',  attrs: { 'data-value': '2026-05-27T14:35', 'data-test-state': 'focus' } },
  { name: '_filled-active', id: 'dtf-filled-active', attrs: { 'data-value': '2026-05-27T14:35', 'data-test-state': 'active' } },
  { name: '_disabled-empty', id: 'dtf-disabled-empty', attrs: { 'data-disabled': '' } },
  { name: '_disabled-filled', id: 'dtf-disabled-filled', attrs: { 'data-disabled': '', 'data-value': '2026-05-27T14:35' } },
  { name: '_invalid-empty', id: 'dtf-invalid-empty', attrs: { 'data-invalid': '' } },
  { name: '_invalid-filled', id: 'dtf-invalid-filled', attrs: { 'data-invalid': '', 'data-value': '2026-05-27T14:35' } },
  { name: '_with-seconds', id: 'dtf-with-seconds', attrs: { 'data-step': '30', 'data-value': '2026-05-27T14:35:00' } },
  // 12-hour locale — shows the AM/PM toggle next to the wheels
  { name: '_twelve-hour', id: 'dtf-12h', attrs: { 'data-value': '2026-05-27T14:35' }, locale: 'en' },
  // Live demo (e2e test target) — unique id so the e2e can scope to a single instance on /
  { name: '_live-demo', id: 'meeting-time', attrs: {} },
]

states.forEach(({ name, id, attrs, locale }) => {
  const content = `{{!-- generated by DateTimeField.generate.ts — do not edit --}}\n${canonical(id, attrs, locale)}\n`
  writeFileSync(resolve(statesDir, `${name}.hbs`), content)
})

// Native reference partials (no DateTimeField wrapper) — the browser's built-in
// <input type="datetime-local"> for each variant, to compare native vs custom
// on real devices.
const nativeInput = (file: string, label: string, attrs: string): void => {
  const id = `dtf-native-${file}`
  writeFileSync(
    resolve(statesDir, `_native-${file}.hbs`),
    `<label for="${id}">${label}</label>\n<input type="datetime-local" id="${id}" name="${id}"${attrs} />\n`,
  )
  console.log(`  _native-${file}.hbs`)
}

console.log(`Generated ${states.length} state partials in ${statesDir}`)
nativeInput('default', 'Datum och tid', ' min="1900-01-01T00:00" max="2100-12-31T23:59" value="2026-05-27T14:35"')
nativeInput('seconds', 'Datum och tid (sekunder)', ' step="1" value="2026-05-27T14:35:30"')
nativeInput('step', 'Datum och tid (15-min steg)', ' step="900" value="2026-05-27T14:30"')
// 12h is decided by the device locale, not an attribute — lang is only honoured by some browsers.
nativeInput('lang-en', 'Datum och tid (lang="en-US")', ' lang="en-US" value="2026-05-27T14:35"')
nativeInput('disabled', 'Datum och tid', ' value="2026-05-27T14:35" disabled')
