import { writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dir = dirname(fileURLToPath(import.meta.url))
const statesDir = resolve(__dir, 'states')
mkdirSync(statesDir, { recursive: true })

function canonical(id: string, attrs: Record<string, string> = {}): string {
  const attrStr = Object.entries(attrs)
    .map(([k, v]) => v === '' ? k : `${k}="${v}"`)
    .join(' ')

  return `<div class="DateTimeField" data-component="DateTimeField" data-id="${id}" data-name="${id}" data-locale="sv-SE" ${attrStr}>
  <input type="datetime-local" class="DateTimeField-native" tabindex="-1" aria-hidden="true">
  <div class="DateTimeField-overlay">
    <div class="Segments" role="group"></div>
    <button class="DateTimeField-trigger" type="button">
      <svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
        <line x1="16" y1="2" x2="16" y2="6"></line>
        <line x1="8" y1="2" x2="8" y2="6"></line>
        <line x1="3" y1="10" x2="21" y2="10"></line>
      </svg>
    </button>
  </div>
  <template class="DateTimeField-calendarTemplate">
    <div class="DateTimeField-popup" role="dialog" aria-modal="true">
      <div class="CalendarInner">
        <div class="CalendarLeft">
          <div class="CalendarHeader">
            <button class="CalendarPrev" type="button"></button>
            <button class="MonthYearTrigger" type="button" aria-expanded="false"><span class="CalendarMonthYear"></span></button>
            <button class="CalendarNext" type="button"></button>
          </div>
          <table class="CalendarGrid" role="grid"></table>
          <div class="YearMonthPicker" hidden>
            <ul class="MonthList" role="listbox" tabindex="0"></ul>
            <ul class="YearList" role="listbox" tabindex="0"></ul>
          </div>
        </div>
        <div class="TimeColumns">
          <ul class="TimeList HourList" role="listbox" tabindex="0"></ul>
          <ul class="TimeList MinuteList" role="listbox" tabindex="0"></ul>
          <ul class="TimeList SecondList" role="listbox" tabindex="0" style="display:none"></ul>
          <ul class="TimeList AmPmList" role="listbox" tabindex="0" style="display:none"></ul>
        </div>
      </div>
      <div class="CalendarFooter">
        <button type="button" class="CalendarFooterClear"></button>
        <button type="button" class="CalendarFooterToday"></button>
        <button type="button" class="CalendarFooterNow"></button>
      </div>
    </div>
  </template>
  <div class="slideContainer"></div>
</div>`
}

const states: { name: string; id: string; attrs: Record<string, string> }[] = [
  { name: '_default', id: 'dtf-default', attrs: {} },
  { name: '_filled', id: 'dtf-filled', attrs: { 'data-value': '2026-05-27T14:35' } },
  { name: '_disabled-empty', id: 'dtf-disabled-empty', attrs: { 'data-disabled': '' } },
  { name: '_disabled-filled', id: 'dtf-disabled-filled', attrs: { 'data-disabled': '', 'data-value': '2026-05-27T14:35' } },
  { name: '_invalid-empty', id: 'dtf-invalid-empty', attrs: { 'data-invalid': '' } },
  { name: '_invalid-filled', id: 'dtf-invalid-filled', attrs: { 'data-invalid': '', 'data-value': '2026-05-27T14:35' } },
  { name: '_with-seconds', id: 'dtf-with-seconds', attrs: { 'data-step': '30', 'data-value': '2026-05-27T14:35:00' } },
  // Live demo (e2e test target) — unique id so the e2e can scope to a single instance on /
  { name: '_live-demo', id: 'meeting-time', attrs: {} },
]

states.forEach(({ name, id, attrs }) => {
  const content = `{{!-- generated by DateTimeField.generate.ts — do not edit --}}\n${canonical(id, attrs)}\n`
  writeFileSync(resolve(statesDir, `${name}.hbs`), content)
})

console.log(`Generated ${states.length} state partials in ${statesDir}`)
